LogolendarzFRONT/Models/ErrorViewModel.cs
namespace LogolendarzFRONT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LogolendarzFRONT/Models/LoginRequestDto.cs
namespace LogolendarzFRONT.Models
{
  public class LoginRequestDto
  {
    public string UserName { get; set; }
    public string Password { get; set; }
  }
}

LogolendarzFRONT/Models/LoginResponseDto.cs
namespace LogolendarzFRONT.Models
{
  public class LoginResponseDto
  {
    public UserDto User { get; set; }
    public string Token { get; set; }
  }
}

LogolendarzFRONT/Models/RegisterRequestDto.cs
namespace LogolendarzFRONT.Models
{
  public class RegisterRequestDto
  {
    public string Id { get; set; }
    public string Email { get; set; }
    public string Name { get; set; }
    public string PhoneNumber { get; set; }
    public string Password { get; set; }
    public string? Role { get; set; }
  }
}

LogolendarzFRONT/Models/RequestDto.cs
using System.Security.AccessControl;
using static LogolendarzFRONT.Utility.SD;

namespace LogolendarzFRONT.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

LogolendarzFRONT/Models/ResponseDto.cs
namespace LogolendarzFRONT.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }
        public bool IsSucces { get; set; } = true;
        public string Message { get; set; } = "";
    }
}

LogolendarzFRONT/Models/UserDto.cs
namespace LogolendarzFRONT.Models
{
  public class UserDto
  {
    public string Id { get; set; }
    public string Email { get; set; }
    public string Name { get; set; }
    public string PhoneNumber { get; set; }
  }
}

LogolendarzFRONT/Models/VisitDto.cs
namespace LogolendarzFRONT.Models
{
    public class VisitDto
    {
        public int VisitId { get; set; }
        public int SpeechTherId { get; set; }
        public int PatientId { get; set; }
        public DateTime VisitDate { get; set; }
        public DateTime LastUpdated { get; set; }
        public DateTime Created { get; set; }
    }
}

LogolendarzFRONT/Controllers/HomeController.cs
using LogolendarzFRONT.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LogolendarzFRONT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LogolendarzFRONT/Controllers/VisitController.cs
using LogolendarzFRONT.Models;
using LogolendarzFRONT.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace LogolendarzFRONT.Controllers
{
    public class VisitController : Controller
    {
        private readonly IVisitService _visitService;

        public VisitController(IVisitService visitService)
        {
            _visitService = visitService;
        }

        public async Task<IActionResult> VisitIndex()
        {
            List<VisitDto>? list = new();
            ResponseDto? response= await _visitService.GetAllVisitsAsync();

            if(response!=null && response.IsSucces) 
            {
                list = JsonConvert.DeserializeObject<List<VisitDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }
    }
}

LogolendarzFRONT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LogolendarzFRONT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogolendarzFRONT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LogolendarzFRONT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LogolendarzFRONT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visit" asp-action="VisitIndex">Visit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LogolendarzFRONT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>